# Generated by Django 4.1 on 2022-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpaddle", "0004_auto_20210119_0436"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancellation_effective_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
