# Generated by Django 4.1 on 2022-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpaddle", "0005_subscription_cancellation_effective_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
