# Generated by Django 4.1 on 2022-12-16 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djpaddle", "0006_subscription_custom_data"),
        migrations.swappable_dependency(settings.DJPADDLE_SUBSCRIBER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.DJPADDLE_SUBSCRIBER_MODEL,
            ),
        ),
    ]
