# Generated by Django 4.1 on 2022-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpaddle", "0007_alter_subscription_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
